### ISSUE TITLE
Error while cloning dotfiles as Normal repo

### ISSUE THREAD

**Issue by semeer37** [GR3YH4TT3R93/dotfiles#3]
![Screenshot_2024-07-28-16-22-12-92_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/7b60f759-00c8-469b-860f-ff7242cc2a9e)

**Comment by GR3YH4TT3R93** [comment]
Sorry for the inconvenience, the updated README [here](https://github.com/GR3YH4TT3R93/dotfiles#clone-dotfiles-as-normal-repo) should hopefully address the issue.

**Comment by semeer37** [comment]
https://github.com/user-attachments/assets/46cdd663-b1c5-48a7-9f48-01a99c82da75

**Comment by GR3YH4TT3R93** [comment]
The issue with gh copilot should be fixed in the latest commit.

If you'd like the startup to be faster, comment out the `if` statement at line 7-9 of `.zshrc` to disable running tmux on startup

**Comment by GR3YH4TT3R93** [comment]
For the temprature permission denied error,

```bash
cd $PREFIX/etc/motd
mv 25-android-temp 25-android-temp.disabled
```

**Comment by GR3YH4TT3R93** [comment]
To exit tmux and termux cleanly, press Ctrl+d (will detach from current tmux session and exit termux) or there's the optional alias `q` for exit (faster than typing exit, similar to vim motions)
